### ISSUE TITLE
Wrong switch command send from Openhab

### ISSUE THREAD

**Issue by mpietrusa** [cartemere/org.openhab.binding.rflink#3]
Hi,
The problem what I have found is related with send command for switch with protocol Tristate. 
When I press button on remote I see in openhab:
`13:13:37.521 [DEBUG] [flink.connector.RfLinkSerialConnector] - <<< 20;10;TriState;ID=808aa1;SWITCH=10;CMD=ON;
13:13:37.531 [DEBUG] [ng.rflink.handler.RfLinkBridgeHandler] - Message received: Raw data = 20;10;TriState;ID=808aa1;SWITCH=10;CMD=ON;, Seq number = 16, Device name = TriState, Device ID = 808aa1-10, Command = ON, Contact = OPEN, running against 9 listeners
13:13:37.538 [DEBUG] [iscovery.RfLinkDeviceDiscoveryService] - Received: bridge: rflink:bridge:gateway message: Raw data = 20;10;TriState;ID=808aa1;SWITCH=10;CMD=ON;, Seq number = 16, Device name = TriState, Device ID = 808aa1-10, Command = ON, Contact = OPEN
13:13:37.548 [DEBUG] [.binding.rflink.handler.RfLinkHandler] - Message from bridge rflink:bridge:gateway from device [TriState-808aa1-10] type [RfLinkSwitchMessage] matched
13:13:37.558 [DEBUG] [.binding.rflink.handler.RfLinkHandler] - Update channel: contact, state: OPEN
13:13:37.568 [DEBUG] [.binding.rflink.handler.RfLinkHandler] - Update channel: command, state: ON
13:13:37.587 [INFO ] [smarthome.event.ItemStateChangedEvent] - TriState_Command changed from OFF to ON`
When I press item in UI Openhab:
`13:12:31.160 [INFO ] [smarthome.event.ItemStateChangedEvent] - TriState_Command changed from OFF to ON
13:12:31.200 [DEBUG] [ng.rflink.handler.RfLinkBridgeHandler] - Transmitting message 'Raw data = unknown, Command = ON, Contact = OPEN'
13:12:31.224 [DEBUG] [ing.rflink.messages.RfLinkBaseMessage] - Decoded message to be sent: 10;TriState;00808aa1;10;ON;, deviceName: TriState, deviceChannel: 808aa1, primaryId: 10
13:12:31.246 [DEBUG] [flink.connector.RfLinkSerialConnector] - Send data (after 0ms, len=28): 31303B54726953746174653B30303830386161313B31303B4F4E3B0A
13:12:31.717 [DEBUG] [flink.connector.RfLinkSerialConnector] - <<< 20;09;OK;
13:12:31.726 [DEBUG] [ng.rflink.handler.RfLinkBridgeHandler] - Message not supported, data: 20;09;OK;`
The problem is Openhab send 10;TriState;**00**808aa1;10;ON; instead 10;TriState;808aa1;10;ON;

Please solve the problem it blocks me to move to openhab because my switches not work

**Comment by cartemere** [comment]
duplicate from cyrilcc#47 : we will proceed on the other thread :)
